name: Go

on:
  push:
  pull_request:
  create:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.22.1"

      - name: Install golangci-lint
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.56.2

      - name: Lint
        run: golangci-lint run ./...

      - name: Test
        run: go test -v ./...

      - name: Build
        if: startsWith(github.event.ref, 'refs/tags/')
        run: go build -v ./...
